# Use postgres/example user/password credentials
version: '3.1'

services:

  frontend:
    image: react-fe
    container_name: frontend
    ports:
      - 8081:80
    build: 
      dockerfile: frontend.Dockerfile
      context: .